export const ACTION_WEATHER_FETCHED = 'ACTION_WEATHER_FETCHED';
export const ACTION_WEATHER_QUERY = 'ACTION_WEATHER_QUERY';

export const ACTION_JOKE_QUERY = 'ACTION_JOKE_QUERY';
export const ACTION_JOKE_FETCHED = 'ACTOIN_JOKE_FETCHED';
export const ACTION_JOKE_CLEAR = 'ACTION_JOKE_CLEAR';
export const ACTION_JOKE_CLEARED = 'ACTION_JOKE_CLEARED';